### ISSUE TITLE
Update to Goomba 2019-05-04

### ISSUE THREAD

**Issue by veikkos** [Sterophonick/SimpleLight#4]
Hi!

As you probably noticed I patched latest Goomba 2019-05-04 to my kernel fork. There was a [request in Reddit](https://www.reddit.com/r/flashcarts/comments/f0p52w/unofficial_ez_flash_omega_kernel_with_latest/fgw6i2l?utm_source=share&utm_medium=web2x) from user of your kernel to update Goomba also to your kernel. Would you like that I'd make a Pull Request?

**Comment by Sterophonick** [comment]
Yeah, I saw that! That was amazing!
Please do!

**Comment by Sterophonick** [comment]
I got it in.
Thank you for doing this!

**Comment by veikkos** [comment]
> I got it in.
> Thank you for doing this!

You were quick, I didn't even have time to make a PR!

Unfortunately I'm having a problem with your fork in general. I flashed your `ezkernel-light.bin` and `ezkernel-dark.bin` from master, but it always gets stuck when trying to start a game. Something about "Saver error, SD Card" (it's bit hard to read it).

Same issue happens if compiling kernel locally. Kernel menus work fine. No matter if I try Dark/Light or reflash, always the same. When restoring official kernel or my fork it again works ok.

Have you tried that it works for you? Because of that issue I wasn't able to test the updated Goomba.

**Comment by Sterophonick** [comment]
Your saves are corrupted. You need to clean off your SD card with chkdsk or
some equivalent. Back. Up. Your. Saves.

**Comment by veikkos** [comment]
I'm not sure how my saves work after restoring original kernel or mine? I also tried to rename "SAVER" folder so that it would be re-created, but it didn't help. I'll see if I can find another SD card to experiment more freely. Good if everything works for you. 👍 

Also, please consider updating version number, any release notes/manual and `ezkernel-light.bin` and `ezkernel-dark.bin` to avoid any confusion.

**Comment by Sterophonick** [comment]
Uh, chkdsk might help with the saves.

**Comment by veikkos** [comment]
My saves are fine. They work ok with official or my kernel. I'll open another issue for what I have.
