### ISSUE TITLE
Cannot start games

### ISSUE THREAD

**Issue by veikkos** [Sterophonick/SimpleLight#5]
**"SAVER err SD-Card"**

Freshly formated SD-card and installed [kernel](https://github.com/Sterophonick/SimpleLight/blob/master/omega-kernel.gba). Also tried older `ezkernel-dark.bin` and `ezkernel-light.bin`. Have tried 2 SD-cards. No trouble with official kernel.

Kernel menus work fine, but all attempts to start a game end up with:

![kuva](https://user-images.githubusercontent.com/24453333/74105928-b2680700-4b6a-11ea-8519-256aeee87183.png)

Gameboy Advance SP AGS-001 + EZ Flash Omega

**Comment by Sterophonick** [comment]
Did you create the SYSTEM folder with the SAVER and other folders?

**Comment by veikkos** [comment]
Ahaa, yes, after copying the `SYSTEM` folder from repo to the SD card it works. That step is not required with official kernel nor did I notice it mentioned in the manual. So I'd suggest that it would be added with clear note to somewhere where users can see it.

Thanks. 👍
