### ISSUE TITLE
RTC offset per game setting?

### ISSUE THREAD

**Issue by nonchip** [Sterophonick/SimpleLight#7]
since various games seem to disagree on how to actually use the RTC, i've noticed the time ingame differing from the time in the menu (and between games) and was wondering if there was a way to configure a custom offset per game (as in "when booting this rom, add 2 hours to the time" config files).
this would probably also fit with other per game settings such as the enabled cheats, save type, bootup mode, etc, which i don't think are currently actually saved but might be a nice addition. shouldn't be too much overhead to just put a bunch of e.g. `.ini` files somewhere in `SYSTEM/`?

**Comment by Sterophonick** [comment]
While that would be cool, I think it would be more work than it's worth.
