### ISSUE TITLE
gba code with kernel access in OS mode?

### ISSUE THREAD

**Issue by nonchip** [Sterophonick/SimpleLight#8]
I'm looking to write some homebrew code that interfaces the SD card in "OS mode", to essentially provide remote SD card access to transfer files between devices via link port, is it possible to have the kernel just load and call code without resetting into "game mode"? or do i need to switch it back into OS mode somehow to enable the IO map for the SDcard and then implement my own FAT access?

**Comment by Sterophonick** [comment]
Good question.
Unfortunately, I don't have a very good answer.

**Comment by nonchip** [comment]
guess when i figure something out i'll tell you then :)

right now i'm struggling with the fact pretty much any affordable link cable nowadays is a chinese knockoff with "unimportant" pins such as GND missing, which somehow makes them still work in commercial games (beats me how), but refuse to work with my code, so i gotta figure that out before i can try to implement any remote access anyway :P

**Comment by nonchip** [comment]
still not having my link stuff implemented so no progress there, but researching sd access with flashcarts i've come across libfat's DLDI (dynamically linked device interface), essentially an API, first developed for DS homebrew, but compatible with GBA, so the user (or flashcart, some do that automatically) can just patch a small function to (low level) talk to the SD cart into the rom, which then libfat linked into the rom can take and do the high level file access stuff.

not much info is available (that i can find) anymore, i found https://web.archive.org/web/20100622175454/http://chishm.drunkencoders.com/DLDI/, and especially the source code for the ezflash IV's DLDI: https://web.archive.org/web/20150425000640/http://chishm.drunkencoders.com/DLDI/downloads/ezsd.zip

do you think this could be easily ported to this device? i tried looking into the firmware code but can't wrap my head around it :/

but from what i gathered it should be possible to do a wrapper that implements something like this:
- switch the cart into "OS mode" (according to the [hardware docs](https://github.com/Sterophonick/SimpleLight/blob/master/docs/EZ-FLASH%20OMEGA%20DOCUMENT.pdf) that would be `SetRompage(0x8000)`, however that's actually done)
- then use the SD functions from [Ezcard_OP.h](https://github.com/Sterophonick/SimpleLight/blob/master/source/Ezcard_OP.h) to do the actual interaction
- switch it back to "game mode" with `SetRompage(0)`

might have to do all of that in code copied to RAM beforehand, since we're switching rom pages, probably masking whatever game rom is currently loaded, but that sounds possible still.

so now i just need to figure out what `SetRompage` actually *means* in terms of "send this and that to such and such register" (because i'd have to reimplement that with e.g. libgba, since i won't have access to any kernel code from inside the game), then i could try implementing this.

so far from [Ezcard_OP.c](https://github.com/Sterophonick/SimpleLight/blob/master/source/Ezcard_OP.c#L162) i gather it could maybe be as easy as just copying the function:

```C
void SetRompage(u16 page)
{
    *(vu16 *)0x9fe0000 = 0xd200;
    *(vu16 *)0x8000000 = 0x1500;
    *(vu16 *)0x8020000 = 0xd200;
    *(vu16 *)0x8040000 = 0x1500;
    *(vu16 *)0x9880000 = page;//C4
    *(vu16 *)0x9fc0000 = 0x1500;
}
```

but i have no idea what those addresses actually do and don't know if i'll screw up my cart if i just fiddle around with that stuff, do you have more insight maybe?

**Comment by Sterophonick** [comment]
I think I once saw a version of LibFAT with EZ-Flash Omega SD support.

Try it and see if it works
https://github.com/felixjones/ezfo-disc_io

**Comment by nonchip** [comment]
that looks like exactly what i was trying to do, thanks a lot! :heart_eyes_cat:
