### ISSUE TITLE
Cheats does not work

### ISSUE THREAD

**Issue by Kashouryo** [Sterophonick/SimpleLight#9]
Hi! I just installed this light theme, and it looks awesome. However, I found that cheats do not work on this version. The "cheat" button does not appear even I have correct rom selected.

**Comment by Kashouryo** [comment]
Tested on official Kernel 1.07(closed source) and Firmware 7.0, cheat works fine.

**Comment by Sterophonick** [comment]
You need to have the CHEAT folder installed to the SYSTEM directory. You
can get this from the official EZ-Flash website.

**Comment by Kashouryo** [comment]
Thank you for the information! It works now!
